services:
  xray-tcp:
    build: .
    container_name: xray-tcp
    ports:
      - 443:80
    environment:
      - PROTOCOL=tcp
      - LOG_LEVEL=debug
      - USER_ID_DIRECT=facade00-0000-4000-a000-000000000000
      - USER_ID_WARP=decade00-0000-4000-a000-000000000000
      - WARP_ADDRESS=warp
      - GENERATE_DIRECT_CONFIGS=true
      - GENERATE_TUNNEL_CONFIGS=true
      - GENERATE_WARP_CONFIGS=true
      - TUNNEL_IP=81.81.81.81

  xrayng-tcp:
    image: ghcr.io/mehdi-behrooz/freiheit-xrayng:latest
    container_name: xray-tcp-tester
    depends_on:
      - xray-tcp
    environment:
      - SUBSCRIPTION_URL=http://xray-tcp:81/
      - ASSERT_COUNT=4
      - INDEX_TO_CHECK=1
      - PERIOD_IN_MINUTES=1

  debugger:
    image: ghcr.io/mehdi-behrooz/docker-debugger:latest
    container_name: debugger

networks:
  default:
    enable_ipv6: true
