services:
  xray-ws:
    build: .
    container_name: xray-ws
    environment:
      - PROTOCOL=ws
      - LOG_LEVEL=debug
      - USER_ID_DIRECT=facade00-0000-4000-a000-000000000000
      - USER_ID_WARP=decade00-0000-4000-a000-000000000000
      - WS_HOST=myhost.com
      - WS_PATH=/xray/
      - WARP_ADDRESS=warp
      - GENERATE_DIRECT_CONFIGS=true
      - GENERATE_WORKER_CONFIGS=true
      - GENERATE_WARP_CONFIGS=true
      - CLOUDFLARE_IP=some.website.com
      - WORKER_SNI=myworker.cf.workers.dev

  xrayng-ws:
    image: ghcr.io/mehdi-behrooz/freiheit-xrayng:latest
    container_name: xray-ws-tester
    depends_on:
      - xray-ws
    environment:
      - SUBSCRIPTION_URL=http://xray-ws:81/
      - ASSERT_COUNT=4
      - PERIOD_IN_MINUTES=1

  debugger:
    image: ghcr.io/mehdi-behrooz/docker-debugger:latest
    container_name: debugger

networks:
  default:
    enable_ipv6: true
